### ISSUE TITLE
Not able to compile

### ISSUE THREAD

**Issue by WePlayOffical** [quanshousio/ToastUI#15]
After pod install, xcode not able to find the ".toast" modifier

"Value of type 'Button<some View>' has no member 'toast'"

**Comment by quanshousio** [comment]
Thank you for the report. I will push a fix shortly. In the meantime, you can use Swift Package Manager to install ToastUI instead.

**Comment by quanshousio** [comment]
Have you imported the ToastUI library? Like putting `import ToastUI` at the top of your file?

**Comment by quanshousio** [comment]
I'm going to close this until further information is provided.
