### ISSUE TITLE
Custom toast question

### ISSUE THREAD

**Issue by barrylachapelle** [quanshousio/ToastUI#16]
## Pre-requisites:

* [ *] Yes, I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) looking for what I needed
* [ *] No, I did not find what I was looking for

Nice work guys - question how did you pull off the green bottom aligned toast in the animated gif example exactly? Would love to see an example. 

<img width="387" alt="Screen Shot 2020-12-23 at 2 18 42 PM" src="https://user-images.githubusercontent.com/1087169/103041231-a5f26000-452a-11eb-8120-1af6b65cc17b.png">

**Comment by quanshousio** [comment]
You can have a look at the `CustomizedToastWithoutToastViewExample` in `AdvancedExamples.swift` in `ToastUISample` for more detail. Here's how that view is laid out.

```swift
struct ContentView: View {
  var text: String

  var body: some View {
    VStack {
      Spacer()
      Text(text)
        .bold()
        .foregroundColor(.white)
        .padding()
        .background(Color.green)
        .cornerRadius(8.0)
        .shadow(radius: 4)
        .padding()
    }
  }
}
```

`VStack` is already vertically centered and padded by default. You need to add a `Spacer` to push the view downward.

**Comment by quanshousio** [comment]
You can have a look at the `CustomizedToastWithoutToastViewExample` in `AdvancedExamples.swift` in `ToastUISample` for more detail. Here's the snippet of that example describing the view.

```swift
struct ContentView: View {
  var text: String

  var body: some View {
    VStack {
      Spacer()
      Text(text)
        .bold()
        .foregroundColor(.white)
        .padding()
        .background(Color.green)
        .cornerRadius(8.0)
        .shadow(radius: 4)
        .padding()
    }
  }
}
```

`VStack` is already vertically centered and padded by default, then a `Spacer` is used to push the view downward.

**Comment by barrylachapelle** [comment]
Ack missed the AdvancedExamples - apologies, and thanks for the response. Nice work again.
