### ISSUE TITLE
IndefiniteProgressToastViewStyle has spinner constantly moving from top left to the toast

### ISSUE THREAD

**Issue by roddymunro** [quanshousio/ToastUI#2]
Before I start, great repository here. It's been great to work with.

I've encountered a weird issue when implementing `toast` using `IndefiniteProgressToastViewStyle()` with a network request. For the duration of the request, the spinner will repeatedly move from the top left of the screen into the center of the toast. Once the request is complete, the toast disappears as expected.

Here's a gif of the issue: https://giphy.com/gifs/VgHGygxhGNeB3zIhS2

This is happening on iPhone 11 Pro Max simulator, Xcode 12 beta 4, iOS 14 beta 4. 

Code example:
```
var body: some View {
        TabView(selection: $selection) {
            NavigationView {
                Text("my view")
            }
            .tabItem {
                Label("Test", systemImage: "book")
                    .imageScale(.large)
                    .accessibility(label: Text("Test"))
            }
        }
        .toast(isPresented: $showLoadingView) {
          ToastView("Loading...")
            .toastViewStyle(IndefiniteProgressToastViewStyle())
        }
        .onAppear {
            showLoadingView = true
            model.loadAllData { result in
                switch result {
                    case .success:
                        showLoadingView = false
                    case .failure(let error):
                        // show error stuff
                }
            }
        }
    }
```

**Comment by quanshousio** [comment]
Thank you for taking the time to try `ToastUI`, I truly appreciate that.

The bug is indeed reproducible on iOS 14 beta 4 but strangely not on iOS 13.6. I just pushed a fix (92035e93610d21d7f354ff7dd47e7dbfe74e9856) on the `hotfix-1.0.1` branch. Would you mind testing it out? If all goes well, I will merge back to the `master` branch.

**Comment by LucasCarioca** [comment]
Just tested on iOS 14 beta 4 and it is resolved in that `hotfix` branch 🎉 

![Screen Shot 2020-08-11 at 10 59 48 PM](https://user-images.githubusercontent.com/13397173/89973610-5e77d100-dc26-11ea-8a62-5655fd49beb4.png)

**Comment by roddymunro** [comment]
Yep that seems to have fixed it for me. Thank you for the quick resolution!
