### ISSUE TITLE
ToastUI Warning attempt to dismiss from view controller (thousands) on 1.3.x

### ISSUE THREAD

**Issue by rocketraman** [quanshousio/ToastUI#20]
## Pre-requisites:

* [X] Yes, I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) looking for what I needed.
* [X] No, I did not find what I was looking for.

## Expected Behavior

With ToastUI 1.3.2 whenever my toasts appear, I get thousands of errors that look like this:

```
2021-02-25 13:48:22.726 iosApp[93595:9719510] Warning: Attempt to dismiss from view controller <_TtGC7SwiftUI19UIHostingControllerGVS_15ModifiedContentGS1_GS1_GS1_GS1_V6iosApp8MainViewGVS_30_EnvironmentKeyWritingModifierGSqCS2_8AppState___GS4_GSqCS2_4User___GS4_GSqCS2_7Checkin___GS4_GSqCS2_4Team___GS4_GSqCS2_5Score____: 0x7faf04419390> while a presentation or dismiss is in progress!
```

I don't know if this is something I'm doing wrong with how I'm using ToastUI or a bug in ToastUI 1.x, BUT if I upgrade to ToastUI 2.0.0, the issue goes away with my code remaining the same, so I suspect this is a bug in 1.x.

However, I see that 2.0.0 no longer supports ios 13. We don't want to raise the minimum compat level for our app.

## Current Behavior

Thousands of Warning messages when attempting to use ToastUI 1.3.0.

## Possible Solution

We could have upgraded to 2.0.0 which fixes the issue, but can't right away since the minimum iOS version has been bumped.

## Your Environment

* Swift Version: 5
* Xcode Version:  12
* Operating System Version: 11.2.1
* Device or Simulator: iPhone 11 13.5

**Comment by quanshousio** [comment]
Would you mind providing more detail about your reproducible example? ToastUI 2.0.0 does indeed remove support for iOS/tvOS 13.0 so unfortunately you have to make a fork for now.

**Comment by rocketraman** [comment]
Example of use that was causing issues, the `.toast` call is on an `AppBackground`:

```
      .toast(isPresented: self.$user.showUserNotDefinedToast) {
        ToastViewWithButton(
          message: "Your email is not recognized.",
          toastToggle: self.$user.showUserNotDefinedToast
        )
      }
```

FYI, I migrated this to a standard SwiftUI alert and it works fine:

```
      .alert(
        isPresented: self.$user.showUserNotDefinedToast,
        content: { Alert(title: Text("Your email is not recognized.")) }
      )
```

**Comment by quanshousio** [comment]
Most of the important changes between v1 and v2 are just adding support for macOS 11.0 and removing support for iOS/tvOS 13.0 for more consistency in the implementation. There is no difference between v1 and v2 in presenting/dismissing the view controller.

Have you tried using the v1 on iOS/tvOS 14.0 to see if the error goes away? If it does, the error might be related to SwiftUI internals. My apologies for not having a clear solution for the error right now.

**Comment by rocketraman** [comment]
> Have you tried using the v1 on iOS/tvOS 14.0 to see if the error goes away? If it does, the error might be related to SwiftUI internals. My apologies for not having a clear solution for the error right now.

I did not try that, but yeah, that would be a good test. I'll give it a shot when I have some time.

**Comment by rocketraman** [comment]
FYI it seems to work fine on iOS 14 with ToastUI 1.x.

**Comment by quanshousio** [comment]
Thanks for your information. You can try to fork the repo and rollback to commit 6fd9e8f4ea92e45155e5530f3762d0f394831c87, which is the PR for v1.3.2. Replace line 50 in the file `ToastViewModifier.swift` with the snippet below to see if it mitigates the issue.

```swift
if !(rootViewController?.isBeingDismissed ?? true) {
  rootViewController?.dismiss(animated: true, completion: onDismiss)
}
```
