### ISSUE TITLE
Compiler Warning since ios15

### ISSUE THREAD

**Issue by scherhak** [quanshousio/ToastUI#26]
Hi,

I get a warning since i updated to iOS 15:
.../ToastUI/ToastViewEnvironmentKey.swift:13:16: 
Expected member name or constructor call after type name

I use ToastUI version 2.0.0

Beste regards

![ios15toastui1](https://user-images.githubusercontent.com/4221861/149618017-1537ae33-7228-4ae4-a5a9-f8f5f1b44bbe.png)

**Comment by quanshousio** [comment]
Thanks for your report. Fixed in version [`3.0.0`](https://github.com/quanshousio/ToastUI/releases/tag/3.0.0).
