### ISSUE TITLE
Improve compile time

### ISSUE THREAD

**Issue by skywalkerlw** [quanshousio/ToastUI#27]
Currently, I can see it takes >2 seconds to get compiled. Is there any way to improve?

![image](https://user-images.githubusercontent.com/2090084/153967568-77f5cff7-035b-4a8e-b5ce-087f1733bae7.png)

**Comment by quanshousio** [comment]
Can you try the new [`3.0.0`](https://github.com/quanshousio/ToastUI/releases/tag/3.0.0) version on latest Xcode 13.3 to see if it reduces the compile time to some extent? This mostly depends on the compiler performance and your computer hardware. `ToastUI` is already quite small with around ~1k LoCs, so it is not trivial to improve the compile time further.

**Comment by quanshousio** [comment]
This issue has been closed due to inactivity. Please feel free to reopen it if you have any further questions.
