### ISSUE TITLE
After Toast dismiss and auto push to next View ,  NavigationBar height not correct

### ISSUE THREAD

**Issue by ACFancy** [quanshousio/ToastUI#32]
## Pre-requisites:

* [ ] Yes, I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) looking for what I needed.
* [ ] No, I did not find what I was looking for.

## Expected Behavior
  when toast dismiss and auto push to next view , NavigationBar height should be correct
![image](https://user-images.githubusercontent.com/10044815/185865171-580034de-4d8f-41dc-9e2c-1f319f55044d.png)

## Current Behavior
   when toast dismiss and auto push to next view , NavigationBar height isn't correct
![image](https://user-images.githubusercontent.com/10044815/185865074-6647a409-801c-4666-9d74-1c747d74c076.png)

## Possible Solution
 maybe code implement leads the bug

## Steps to Reproduce
 - toast loading
 - dismiss toast and auto push to next view in swiftUI
 - NavigationBar height of next view height isn't correct

## Your Environment

* Swift Version:  5.6
* Xcode Version:  13.3
* Operating System Version: macOS 12.4
* Device or Simulator: iOS 15 iPad mini 6

**Comment by quanshousio** [comment]
Hi @ACFancy, is this still happening on newer iOS versions?

**Comment by quanshousio** [comment]
This issue has been closed due to inactivity. Please feel free to reopen it if you have any further questions.
