### ISSUE TITLE
Is there any way to custom the animation duration?

### ISSUE THREAD

**Issue by Robotxm** [quanshousio/ToastUI#35]
## Pre-requisites:

* [x] Yes, I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) looking for what I needed
* [ ] No, I did not find what I was looking for

## Feature Suggestion

Is there any way to specify the animation duration? It seems that current duration is 0.4 and cannot be modified by caller.

**Comment by quanshousio** [comment]
Unfortunately, no. ToastUI uses [UIModalTransitionStyle.crossDissolve](https://developer.apple.com/documentation/uikit/uimodaltransitionstyle/crossdissolve), so everything related to transition is internally handled by UIKit. I don't have any plans to add custom transition yet. Thanks for the suggestion.

**Comment by Robotxm** [comment]
Got it. Thanks for reply.
