### ISSUE TITLE
Failing to compile when added as a swift package

### ISSUE THREAD

**Issue by LucasCarioca** [quanshousio/ToastUI#4]
I wanted to try the package out a bit and I added it to a brand new project and it fails to compile.

There is nothing else in the project and it is showing a failure when compiling ToastUI. 

Here is the error 

```
loading unsized types is not allowed
  load void, void* %53, align 8, !dbg !316
Function return type does not match operand type of return inst!
  ret void <badref>, !dbg !316
 doublein function $s7ToastUI07DefaultA9ViewStyleV0caD0V11_cornerSize33_E64FDF835852504B4904DF0A39BD1713LLAA20ScaledMetricPropertyVy12CoreGraphics7CGFloatVGvpfi
<unknown>:0: error: fatal error encountered during compilation; please file a bug report with your project and the crash log
<unknown>:0: note: Broken function found, compilation aborted!
```

**Comment by LucasCarioca** [comment]
Figured out that it has something to do with the machine I'm on. Not caused by this package.

**Comment by quanshousio** [comment]
For more information, I also got this error while compiling on Xcode 11.0 with Swift 5.1. It's so odd that the compiler just crashed when compiling the `ScaledMetricProperty` property wrapper, not sure what's the culprit here. Fortunately, Swift 5.2+ compiles without any problems.
