### ISSUE TITLE
Can I choose to not have background?

### ISSUE THREAD

**Issue by wyk111wyk** [quanshousio/ToastUI#8]
## Pre-requisites:
- [ ] Yes, I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) looking for what I needed
- [ ] No, I did not find what I was looking for

**Comment by quanshousio** [comment]
Yes, you can. As demonstrated in [`CustomizedToastWithoutToastViewExample`](https://github.com/quanshousio/ToastUI/blob/e0d402f908ebf836e8750743b8d9eca085c03ea1/ToastUISample/Shared/AdvancedExamples.swift#L21), you just need to provide your SwiftUI views directly without using `ToastView`. Here's an example using Swift 5.3+.

```swift
struct CustomizedToastWithoutToastViewExample: View {
  @State private var presentingToast: Bool = false

  var body: some View {
    Button {
      presentingToast = true
    } label: {
      Text("Tap me")
    }
    .toast(isPresented: $presentingToast, dismissAfter: 2.0) {
      print("Toast dismissed")
    } content: {
      // your SwiftUI views here
      VStack {
        Spacer()
        Text("You can put any SwiftUI views here without the need of ToastView")
          .bold()
          .foregroundColor(.white)
          .padding()
          .background(Color.green)
          .cornerRadius(8.0)
          .shadow(radius: 4)
          .padding()
      }
    }
  }
}
```

**Comment by quanshousio** [comment]
Yes, you can. As demonstrated in [`CustomizedToastWithoutToastViewExample`](https://github.com/quanshousio/ToastUI/blob/e0d402f908ebf836e8750743b8d9eca085c03ea1/ToastUISample/Shared/AdvancedExamples.swift#L21), you just need to provide your SwiftUI views directly without using `ToastView`. Here's a snippet from that example using Swift 5.3+.

```swift
struct CustomizedToastWithoutToastViewExample: View {
  @State private var presentingToast: Bool = false

  var body: some View {
    Button {
      presentingToast = true
    } label: {
      Text("Tap me")
    }
    .toast(isPresented: $presentingToast, dismissAfter: 2.0) {
      print("Toast dismissed")
    } content: {
      // your SwiftUI views here
      VStack {
        Spacer()
        Text("You can put any SwiftUI views here without the need of ToastView")
          .bold()
          .foregroundColor(.white)
          .padding()
          .background(Color.green)
          .cornerRadius(8.0)
          .shadow(radius: 4)
          .padding()
      }
    }
  }
}
```

**Comment by wyk111wyk** [comment]
But this is for pure Text, can't remove the blur background of success or progress view(ToastView)

**Comment by quanshousio** [comment]
`ToastView` hasn't supported styles without background yet. Thank you for the suggestion and I will push an update in the near future.

**Comment by quanshousio** [comment]
Sorry for the late update but `ToastUI` has just been updated and you can now use `ToastView` with custom background (#11). Here's an example of using `ToastView` with `IndefiniteProgressToastViewStyle` but without blur background.

``` swift
.toast(isPresented: $presentingToast) {
  ToastView("Loading...") {
    // EmptyView()
  } background: {
    // EmptyView()
  }
  .toastViewStyle(IndefiniteProgressToastViewStyle())
}
```

Passing `EmptyView` is optional so you can reduce it to be one-liner.

``` swift
.toast(isPresented: $presentingToast, dismissAfter: 2.0) {
  ToastView("Loading...") {} background: {}
    .toastViewStyle(IndefiniteProgressToastViewStyle())
}
```

The first closure is to provide your custom content view just like before and the second closure is for custom background view. For more information, check out the new `ToastViewWithCustomBackgroundExample` in `ToastUISample`.
